apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    run: eureka-server
spec:
  ports:
    - name: port1
      port: 8761
      nodePort: 31003
      protocol: TCP
  selector:
    run: eureka-server
  type: NodePort
