- hosts: prod
  vars:
    http_port: 80
    max_clients: 200
  remote_user: ec2-user
  tasks:
    - name: copy notebook service jar to prod
      copy: src=notebook-service-1.0.jar dest=/tmp owner=ec2-user group=ec2-user mode=0644
    - name: start notebook service jar
      shell: source ~/.bash_profile; nohup java -jar /tmp/notebook-service-1.0.jar &
    - name: sleep for 20 seconds
      shell: sleep 20
    - name: shutdown notebook service jar
      shell: kill -9 $(/usr/sbin/lsof -t -i:1111)
